remote_theme: just-the-docs/just-the-docs

search_enabled: true

---
layout: default
title: From EEG to fMRI
nav_order: 1
---

---
layout: default
title: Documentation
nav_order: 2
---

---
layout: default
title: Separating Sinusoid Projections
nav_order: 2
---
