remote_theme: just-the-docs/just-the-docs

search_enabled: false

title: From EEG to fMRI

color_scheme: dark

exclude: ["README.md"]

compress_html:
	clippings: all
	comments: all
	endings: all
	startings: []
	blanklines: true
	profile: false

mathjax:
	source: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_CHTML
	config: 'MathJax.Hub.Config({ TeX: { equationNumbers: { autoNumber: "AMS" } } })'