remote_theme: just-the-docs/just-the-docs

search_enabled: true

---
layout: default
title: Home
nav_order: 1
---

---
layout: default
title: Documentation
nav_order: 2
---

---
layout: default
title: Sinusoid Separation
nav_order: 2
---
