remote_theme: just-the-docs/just-the-docs

search_enabled: false

---
layout: default
title: README
nav_order: 1
---

---
layout: default
title: Documentation
nav_order: 2
---

---
layout: default
title: Sinusoid Separation Projections
nav_order: 3
---
