#channel relevances
python -u main.py lrp_eeg_channels $1 -topographical_attention -learning_rate 0.0001 -na_path_eeg /home/ist_davidcalhas/eeg_to_fmri/na_models_eeg/na_specification_2 -na_path_fmri /home/ist_davidcalhas/eeg_to_fmri/na_models_fmri/na_specification_2 -verbose -gpu_mem 2000 -batch_size 4 -seed $2
python -u main.py lrp_eeg_channels $1 -fourier_features -random_fourier -topographical_attention -learning_rate 0.0001 -na_path_eeg /home/ist_davidcalhas/eeg_to_fmri/na_models_eeg/na_specification_2 -na_path_fmri /home/ist_davidcalhas/eeg_to_fmri/na_models_fmri/na_specification_2 -verbose -gpu_mem 2000 -batch_size 4 -seed $2

#compare models
python compare.py $1 -name1 \(i\) -name2 \(ii\) -topographical_attention2 -epochs 10 -na_path_eeg /home/ist_davidcalhas/eeg_to_fmri/na_models_eeg/na_specification_2 -na_path_fmri /home/ist_davidcalhas/eeg_to_fmri/na_models_fmri/na_specification_2 -gpu_mem 2000 -verbose -seed $2
python compare.py $1 -name1 \(i\) -name2 \(iii\) -fourier_features2 -random_fourier2 -epochs 10 -na_path_eeg /home/ist_davidcalhas/eeg_to_fmri/na_models_eeg/na_specification_2 -na_path_fmri /home/ist_davidcalhas/eeg_to_fmri/na_models_fmri/na_specification_2 -gpu_mem 2000 -verbose -seed $2
python compare.py $1 -name1 \(i\) -name2 \(iv\)  -topographical_attention2 -fourier_features2 -random_fourier2 -epochs 10 -na_path_eeg /home/ist_davidcalhas/eeg_to_fmri/na_models_eeg/na_specification_2 -na_path_fmri /home/ist_davidcalhas/eeg_to_fmri/na_models_fmri/na_specification_2 -gpu_mem 2000 -verbose -seed $2
python compare.py $1 -name1 \(ii\) -name2 \(iii\)  -topographical_attention1 -fourier_features2 -random_fourier2 -epochs 10 -na_path_eeg /home/ist_davidcalhas/eeg_to_fmri/na_models_eeg/na_specification_2 -na_path_fmri /home/ist_davidcalhas/eeg_to_fmri/na_models_fmri/na_specification_2 -gpu_mem 2000 -verbose -seed $2
python compare.py $1 -name1 \(ii\) -name2 \(iv\)  -topographical_attention1 -topographical_attention2 -fourier_features2 -random_fourier2 -epochs 10 -na_path_eeg /home/ist_davidcalhas/eeg_to_fmri/na_models_eeg/na_specification_2 -na_path_fmri /home/ist_davidcalhas/eeg_to_fmri/na_models_fmri/na_specification_2 -gpu_mem 2000 -verbose -seed $2
python compare.py $1 -name1 \(iii\) -name2 \(iv\)  -fourier_features1 -random_fourier1 -topographical_attention2 -fourier_features2 -random_fourier2 -epochs 10 -na_path_eeg /home/ist_davidcalhas/eeg_to_fmri/na_models_eeg/na_specification_2 -na_path_fmri /home/ist_davidcalhas/eeg_to_fmri/na_models_fmri/na_specification_2 -gpu_mem 2000 -verbose -seed $2